### ISSUE TITLE
API selection/box/profiles not working ?

### ISSUE THREAD

**Issue by gmaze** [donatagiglio/Argovis#3]
Hi @donatagiglio , @tylertucker202 
I've seen that the API access point selection/box/profiles does not seem to work:

For instance the following request
```bash
curl -X GET "https://argovis.colorado.edu/selection/box/profiles?startDate=2019-10-01&endDate=2019-10-04&presRange=%5B618%2C635%5D&llCorner=%5B-160%2C20%5D&urCorner=%5B-150%2C30%5D" -H  "accept: application/json"
```

returns a 404 error

I've found about this when using argovis from argopy:
```python
AdF = ArgoDataFetcher(src="argovis").region([-75, -55, 30.0, 40.0, 0, 100.0, "2011-01-01", "2011-01-15"])
print(AdF.uri)
['https://argovis.colorado.edu/selection/box/profiles?startDate=2011-01-01T00:00:00Z&endDate=2011-01-15T00:00:00Z&presRange=[0,100.0]&llCorner=[-75,30.0]&urCorner=[-55,40.0]']
ds = AdF.load().data
```
raises a ``DataNotFound`` error

any idea what's going on ?

**Comment by katieannemills** [comment]
Hi Guillaume,

Thanks for your question - unfortunately we had to block the `/selection/box/profiles` endpoint as someone was abusing it, causing our servers to crash. You can make similar regional queries with the `/selection/profiles` endpoint, for example:

`https://argovis.colorado.edu/selection/profiles?startDate=2021-11-15T17:38:29Z&endDate=2021-11-29T17:38:29Z&presRange=[0,2000]&shape=[[[170.683594,28.149503],[179.245411,31.7533],[-180,31.998614],[-180,31.998614],[-171.5625,34.741612],[-171.386719,15.623037],[-179.953058,22.130459],[-180,22.160635],[-180,22.160635],[170.683594,28.149503]]]`

where those coordinates form a polygon region. Today, if you don't want to pick points for your polygon by hand, you can generate a URL like the example above by clicking on the pentagon icon on argovis' homepage, drawing your polygon, and clicking on To Selection Page. In future we'll be implementing better protections against the abuses that led to temporarily blocking the box search; look for those early in the new year.

Please let me know any further questions and we'll be happy to help.

**Comment by gmaze** [comment]
Thanks @BillMills for your answer
I'll implement the new endpoint in argopy then

About the multiple requests, can you id where is this coming from ?
I'm asking because, for someone using argopy, it can be very easy to trigger a lot of request to argovis without even knowing it, may be argovis could id "legitimate" calls ?

**Comment by katieannemills** [comment]
@gmaze not at this time, unfortunately - all calls are anonymous. But, that's going to change in the near future; we'll be requiring API tokens that will identify users and limit their request rates in order to properly solve this problem and allocate server resources more fairly. There'll be a transition period before API tokens are firmly required, when we can talk about helping argopy integrate with this refactor; I'll be in touch when the feature is a bit more mature.

**Comment by gmaze** [comment]
great, it will be fun to implement this auth system
(hopefully, this will not open the way to a paid service ...)

**Comment by katieannemills** [comment]
Argovis will always be a free service. To give you a technical preview, it's going to be really simple - API requests will just require a header `x-argokey` with an API token value which the user will have to supply; I'm not planning on any sophisticated session management at the API level.

**Comment by gmaze** [comment]
Great ! Waiting for this
